# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea59c908c7031589da1d023177467ab5823423f2b77abc02300963d05288e6f0c9738f19e7368a4baaa3e0fd4d45794e95f5ab42725943a6ad45bb72da02811e

test:
  secret_key_base: 0a004174e9063d6da51b9e7511607d1e3799f90e0767b9d64dc20790bf01e484d7b72715f1242a09f9576c64b9d4b0a5480141a9911d9426d326c18857e3cf23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
